// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaAdopcion.Api.Data;

#nullable disable

namespace SistemaAdopcion.Api.Data.Migrations
{
    [DbContext(typeof(PetContext))]
    partial class PetContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaAdopcion.Api.Data.Entities.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdoptionStatus")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Views")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdoptionStatus = 1,
                            Breed = "Dog - Golden Retriever",
                            DateOfBirth = new DateTime(2021, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Buddy is a friendly and playful Golden Retriever, known for being great with kids and other pets. He enjoys long walks and cuddling on the couch. Buddy is fully vaccinated and ready to bring joy to your family.",
                            Gender = 0,
                            Image = "img_1.jpg",
                            IsActive = true,
                            Name = "Buddy",
                            Price = 300.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 2,
                            AdoptionStatus = 1,
                            Breed = "Cat - Siamese",
                            DateOfBirth = new DateTime(2020, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Whiskers is an elegant Siamese cat who adores attention and loves to cuddle with her humans. She has stunning blue eyes and a soft coat. Whiskers is spayed and ready to be your feline companion.",
                            Gender = 1,
                            Image = "img_2.jpg",
                            IsActive = true,
                            Name = "Whiskers",
                            Price = 150.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 3,
                            AdoptionStatus = 1,
                            Breed = "Dog - German Shepherd",
                            DateOfBirth = new DateTime(2019, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Rocky is a loyal and protective German Shepherd, ideal for an active family or an individual seeking a faithful companion. He's well-trained and loves outdoor adventures.",
                            Gender = 0,
                            Image = "img_3.jpg",
                            IsActive = true,
                            Name = "Rocky",
                            Price = 400.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 4,
                            AdoptionStatus = 1,
                            Breed = "Rabbit - Himalayan",
                            DateOfBirth = new DateTime(2022, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Luna is a gentle and low-maintenance Himalayan rabbit, making her a perfect first pet. She enjoys hopping around and nibbling on fresh vegetables. Luna is litter-trained and easy to care for.",
                            Gender = 1,
                            Image = "img_4.jpg",
                            IsActive = true,
                            Name = "Luna",
                            Price = 50.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 5,
                            AdoptionStatus = 1,
                            Breed = "Guinea Pig - Abyssinian",
                            DateOfBirth = new DateTime(2023, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Simba is a curious and social Abyssinian guinea pig who thrives on human interaction. He's always excited for playtime and enjoys exploring his surroundings. Simba comes with his own cozy cage and accessories.",
                            Gender = 0,
                            Image = "img_5.jpg",
                            IsActive = true,
                            Name = "Simba",
                            Price = 25.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 6,
                            AdoptionStatus = 1,
                            Breed = "Dog - Labrador Retriever",
                            DateOfBirth = new DateTime(2020, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lucky is a friendly and energetic Labrador Retriever. He loves playing fetch and going for long hikes. Lucky is up to date on vaccinations and is looking for an active family to join.",
                            Gender = 0,
                            Image = "img_6.jpg",
                            IsActive = true,
                            Name = "Lucky",
                            Price = 350.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 7,
                            AdoptionStatus = 1,
                            Breed = "Dog - Beagle",
                            DateOfBirth = new DateTime(2021, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Daisy is a sweet and loving Beagle. She enjoys cuddling on the couch and going for leisurely walks. Daisy is spayed and ready to become your loyal companion.",
                            Gender = 1,
                            Image = "img_7.jpg",
                            IsActive = true,
                            Name = "Daisy",
                            Price = 250.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 8,
                            AdoptionStatus = 1,
                            Breed = "Dog - Bulldog",
                            DateOfBirth = new DateTime(2019, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Max is a gentle and affectionate Bulldog. He's great with children and loves lounging in the sun. Max is microchipped and has a clean bill of health.",
                            Gender = 0,
                            Image = "img_8.jpg",
                            IsActive = true,
                            Name = "Max",
                            Price = 450.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 9,
                            AdoptionStatus = 1,
                            Breed = "Dog - Australian Shepherd",
                            DateOfBirth = new DateTime(2020, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sadie is an intelligent and active Australian Shepherd. She excels in obedience training and enjoys agility courses. Sadie is looking for an owner who shares her love for adventure.",
                            Gender = 1,
                            Image = "img_9.jpg",
                            IsActive = true,
                            Name = "Sadie",
                            Price = 380.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 10,
                            AdoptionStatus = 1,
                            Breed = "Dog - Rottweiler",
                            DateOfBirth = new DateTime(2018, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Rocky is a strong and protective Rottweiler. He's a loyal companion who takes his role as a guard dog seriously. Rocky is well-trained and ready to keep your home safe.",
                            Gender = 0,
                            Image = "img_10.jpg",
                            IsActive = true,
                            Name = "Rocky",
                            Price = 300.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 11,
                            AdoptionStatus = 1,
                            Breed = "Dog - Dachshund",
                            DateOfBirth = new DateTime(2021, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Molly is an adorable Dachshund with a playful personality. She enjoys chasing toys and burrowing under blankets. Molly is spayed and ready to add joy to your home.",
                            Gender = 1,
                            Image = "img_11.jpg",
                            IsActive = true,
                            Name = "Molly",
                            Price = 200.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 12,
                            AdoptionStatus = 1,
                            Breed = "Dog - Yorkshire Terrier",
                            DateOfBirth = new DateTime(2020, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Charlie is a lively Yorkshire Terrier full of energy and charm. He's a social pup who loves meeting new people and other dogs. Charlie is fully vaccinated and eager to find a loving family.",
                            Gender = 0,
                            Image = "img_12.jpg",
                            IsActive = true,
                            Name = "Charlie",
                            Price = 280.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 13,
                            AdoptionStatus = 1,
                            Breed = "Dog - Boxer",
                            DateOfBirth = new DateTime(2018, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bailey is an athletic and friendly Boxer. She enjoys playing fetch in the yard and going on long runs. Bailey is looking for an active owner to share her enthusiasm for life.",
                            Gender = 1,
                            Image = "img_13.jpg",
                            IsActive = true,
                            Name = "Bailey",
                            Price = 400.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 14,
                            AdoptionStatus = 1,
                            Breed = "Dog - Poodle",
                            DateOfBirth = new DateTime(2019, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cooper is a smart and well-mannered Poodle. He's hypoallergenic and great for families with allergies. Cooper is crate-trained and ready to be your well-behaved companion.",
                            Gender = 0,
                            Image = "img_14.jpg",
                            IsActive = true,
                            Name = "Cooper",
                            Price = 320.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 15,
                            AdoptionStatus = 1,
                            Breed = "Dog - Shih Tzu",
                            DateOfBirth = new DateTime(2022, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lucy is a sweet and gentle Shih Tzu who adores cuddles and belly rubs. She has a fluffy coat that requires regular grooming. Lucy is spayed and looking for a loving home.",
                            Gender = 1,
                            Image = "img_15.jpg",
                            IsActive = true,
                            Name = "Lucy",
                            Price = 280.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 16,
                            AdoptionStatus = 1,
                            Breed = "Cat - Siamese",
                            DateOfBirth = new DateTime(2022, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Luna is a graceful Siamese cat with striking blue eyes and a loving personality. She enjoys curling up on the sofa and being pampered. Luna is spayed and ready to bring elegance to your home.",
                            Gender = 1,
                            Image = "img_16.jpg",
                            IsActive = true,
                            Name = "Luna",
                            Price = 180.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 17,
                            AdoptionStatus = 1,
                            Breed = "Cat - Bengal",
                            DateOfBirth = new DateTime(2020, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Leo is a playful and adventurous Bengal cat who loves climbing and exploring. He's highly active and enjoys interactive toys. Leo is neutered and looking for a family who shares his sense of adventure.",
                            Gender = 0,
                            Image = "img_17.jpg",
                            IsActive = true,
                            Name = "Leo",
                            Price = 250.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 18,
                            AdoptionStatus = 1,
                            Breed = "Cat - Ragdoll",
                            DateOfBirth = new DateTime(2019, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Misty is a gentle and affectionate Ragdoll cat with soft, fluffy fur. She enjoys being cradled like a baby and will purr contentedly in your arms. Misty is spayed and ready to be your loving companion.",
                            Gender = 1,
                            Image = "img_18.jpg",
                            IsActive = true,
                            Name = "Misty",
                            Price = 220.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 19,
                            AdoptionStatus = 1,
                            Breed = "Cat - Scottish Fold",
                            DateOfBirth = new DateTime(2021, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Oscar is an adorable Scottish Fold cat known for his unique folded ears and sweet disposition. He's great with children and enjoys napping in warm spots. Oscar is neutered and seeking a cozy home.",
                            Gender = 0,
                            Image = "img_19.jpg",
                            IsActive = true,
                            Name = "Oscar",
                            Price = 190.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 20,
                            AdoptionStatus = 1,
                            Breed = "Cat - Persian",
                            DateOfBirth = new DateTime(2020, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lola is a charming Persian cat with a luxurious long coat and a calm personality. She's used to a life of luxury and enjoys lounging on soft cushions. Lola is spayed and ready for a regal home.",
                            Gender = 1,
                            Image = "img_20.jpg",
                            IsActive = true,
                            Name = "Lola",
                            Price = 270.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 21,
                            AdoptionStatus = 1,
                            Breed = "Cat - Sphynx",
                            DateOfBirth = new DateTime(2020, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Milo is a unique Sphynx cat known for his hairless appearance and affectionate nature. He craves warmth and will snuggle under blankets. Milo is neutered and looking for a cozy lap to call his own.",
                            Gender = 0,
                            Image = "img_21.jpg",
                            IsActive = true,
                            Name = "Milo",
                            Price = 300.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 22,
                            AdoptionStatus = 1,
                            Breed = "Cat - Maine Coon",
                            DateOfBirth = new DateTime(2019, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bella is a majestic Maine Coon cat with a lush, flowing coat and a friendly demeanor. She enjoys exploring the great outdoors and is an excellent mouser. Bella is spayed and ready to rule her kingdom.",
                            Gender = 1,
                            Image = "img_22.jpg",
                            IsActive = true,
                            Name = "Bella",
                            Price = 240.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 23,
                            AdoptionStatus = 1,
                            Breed = "Cat - Russian Blue",
                            DateOfBirth = new DateTime(2021, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Felix is a sleek and elegant Russian Blue cat with a reserved but affectionate personality. He enjoys quiet moments and observing the world from high perches. Felix is neutered and ready to be your sophisticated companion.",
                            Gender = 0,
                            Image = "img_23.jpg",
                            IsActive = true,
                            Name = "Felix",
                            Price = 200.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 24,
                            AdoptionStatus = 1,
                            Breed = "Cat - Egyptian Mau",
                            DateOfBirth = new DateTime(2020, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cleo is a stunning Egyptian Mau cat with distinctive spots and a playful spirit. She loves interactive toys and laser pointers. Cleo is spayed and ready to bring a touch of the exotic to your home.",
                            Gender = 1,
                            Image = "img_24.jpg",
                            IsActive = true,
                            Name = "Cleo",
                            Price = 230.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 25,
                            AdoptionStatus = 1,
                            Breed = "Cat - Scottish Fold",
                            DateOfBirth = new DateTime(2019, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mochi is a charming Scottish Fold cat with an endearing folded ear and a sweet temperament. He's great with children and enjoys curling up in cozy spots. Mochi is neutered and ready for cuddles.",
                            Gender = 0,
                            Image = "img_25.jpg",
                            IsActive = true,
                            Name = "Mochi",
                            Price = 210.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 26,
                            AdoptionStatus = 1,
                            Breed = "Dog - Indian Pariah",
                            DateOfBirth = new DateTime(2019, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Raja is a friendly Indian Pariah dog, known for his loyalty and adaptability. He's great with kids and enjoys long walks. Raja is looking for a loving family to call his own.",
                            Gender = 0,
                            Image = "img_26.jpg",
                            IsActive = true,
                            Name = "Raja",
                            Price = 100.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 27,
                            AdoptionStatus = 1,
                            Breed = "Cat - Indian Shorthair",
                            DateOfBirth = new DateTime(2020, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chandni is a graceful Indian Shorthair cat with a silky coat and a calm demeanor. She enjoys lounging in the sun and being pampered. Chandni is spayed and ready to grace your home.",
                            Gender = 1,
                            Image = "img_27.jpg",
                            IsActive = true,
                            Name = "Chandni",
                            Price = 80.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 28,
                            AdoptionStatus = 1,
                            Breed = "Dog - Rajapalayam",
                            DateOfBirth = new DateTime(2018, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sheru is a majestic Rajapalayam dog with a strong and noble presence. He's an excellent guard dog and is fiercely loyal to his family. Sheru is ready to protect and serve.",
                            Gender = 0,
                            Image = "img_28.jpg",
                            IsActive = true,
                            Name = "Sheru",
                            Price = 200.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 29,
                            AdoptionStatus = 1,
                            Breed = "Cat - Indian Siamese",
                            DateOfBirth = new DateTime(2019, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Meera is a charming Indian Siamese cat with striking blue eyes and a playful personality. She enjoys interactive toys and cuddling with her humans. Meera is looking for a loving home.",
                            Gender = 1,
                            Image = "img_29.jpg",
                            IsActive = true,
                            Name = "Meera",
                            Price = 70.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 30,
                            AdoptionStatus = 1,
                            Breed = "Dog - Mudhol Hound",
                            DateOfBirth = new DateTime(2019, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Krishna is a swift and agile Mudhol Hound, known for his hunting prowess and friendly disposition. He loves outdoor adventures and is looking for an active family.",
                            Gender = 0,
                            Image = "img_30.jpg",
                            IsActive = true,
                            Name = "Krishna",
                            Price = 150.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 31,
                            AdoptionStatus = 1,
                            Breed = "Cat - Indian Persian",
                            DateOfBirth = new DateTime(2019, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Amara is an elegant Indian Persian cat with a luxurious long coat and a calm personality. She enjoys being pampered and lounging in comfort. Amara is spayed and ready for a regal home.",
                            Gender = 1,
                            Image = "img_11.jpg",
                            IsActive = true,
                            Name = "Amara",
                            Price = 90.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 32,
                            AdoptionStatus = 1,
                            Breed = "Dog - Kombai",
                            DateOfBirth = new DateTime(2022, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kumar is a brave and loyal Kombai dog, known for his protective instincts and affectionate nature. He's great with children and is looking for a loving family to guard.",
                            Gender = 0,
                            Image = "img_22.jpg",
                            IsActive = true,
                            Name = "Kumar",
                            Price = 180.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 33,
                            AdoptionStatus = 1,
                            Breed = "Cat - Indian Bobtail",
                            DateOfBirth = new DateTime(2020, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sakshi is an inquisitive Indian Bobtail cat with a distinctive bobbed tail and a playful spirit. She enjoys chasing toys and exploring her surroundings. Sakshi is spayed and ready to brighten your home.",
                            Gender = 1,
                            Image = "img_3.jpg",
                            IsActive = true,
                            Name = "Sakshi",
                            Price = 75.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 34,
                            AdoptionStatus = 1,
                            Breed = "Dog - Himalayan Sheepdog",
                            DateOfBirth = new DateTime(2018, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Arya is a courageous Himalayan Sheepdog, known for her endurance and protective instincts. She's an excellent choice for rural living and is looking for a responsible owner.",
                            Gender = 1,
                            Image = "img_14.jpg",
                            IsActive = true,
                            Name = "Arya",
                            Price = 220.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 35,
                            AdoptionStatus = 1,
                            Breed = "Cat - Indian Mau",
                            DateOfBirth = new DateTime(2020, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Rani is a graceful Indian Mau cat with distinctive spots and a playful spirit. She enjoys interactive toys and sunbathing by the window. Rani is spayed and ready to bring joy to your home.",
                            Gender = 1,
                            Image = "img_25.jpg",
                            IsActive = true,
                            Name = "Rani",
                            Price = 85.0,
                            Views = 0
                        });
                });

            modelBuilder.Entity("SistemaAdopcion.Api.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SistemaAdopcion.Api.Data.Entities.UserAdoption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AdoptedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAdoptions");
                });

            modelBuilder.Entity("SistemaAdopcion.Api.Data.Entities.UserFavorites", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "PetId");

                    b.HasIndex("PetId");

                    b.ToTable("UserFavorites");
                });

            modelBuilder.Entity("SistemaAdopcion.Api.Data.Entities.UserAdoption", b =>
                {
                    b.HasOne("SistemaAdopcion.Api.Data.Entities.Pet", "Pet")
                        .WithMany()
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaAdopcion.Api.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SistemaAdopcion.Api.Data.Entities.UserFavorites", b =>
                {
                    b.HasOne("SistemaAdopcion.Api.Data.Entities.Pet", "Pet")
                        .WithMany()
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaAdopcion.Api.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
