global using CommunityToolkit.Maui.Alerts;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using SistemaAdopcion.Mobile.Models;
global using SistemaAdopcion.Mobile.Pages;
global using SistemaAdopcion.Mobile.ViewModels;
global using SisemaAdopcion.Shared.Dtos;
global using SistemaAdopcion.Mobile.Services;
global using SisemaAdopcion.Shared.Enumerations;
